### ISSUE TITLE
change authentication from http digest to a new secure ECC based authentication scheme

### ISSUE THREAD

**Issue by charan1595** [theintencity/p2p-sip#17]
hi,

my project is to change the existing http digest authentication scheme to a new secure ECC based authentication scheme , here is the link of the scheme : http://www.sciencedirect.com/science/article/pii/S0920548913000895

can yo please let me know, what part of the code should i modify to achieve this.

**Comment by theintencity** [comment]
If you send a copy of this paper PDF to my email, I can take a look.

Without knowing what ECC is, I would think that any authentication related
modification will go in the UserAgent class's authenticate function, where
createAuthorization is called. See near line 1311 and 1315 in

https://github.com/theintencity/p2p-sip/blob/master/src/std/rfc3261.py

The createAuthorization function is imported from rfc2617.py and creates a
basic or digest authorization string. The stack.authenticate in turn calls
the app's authenticate to get the user's credentials, which are then used
in createAuthorization.

Hope this helps!
Mamta




On Sat, Apr 9, 2016 at 12:37 AM, charan1595 <notifications@github.com>
wrote:

> hi,
>
> my project is to change the existing http digest authentication scheme to
> a new secure ECC based authentication scheme , here is the link of the
> scheme :
> http://www.sciencedirect.com/science/article/pii/S0920548913000895
>
> can yo please let me know, what part of the code should i modify to
> achieve this.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/theintencity/p2p-sip/issues/17>
>



-- 
The Intencity Team  http://theintencity.com
