### ISSUE TITLE
python3?

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [theintencity/p2p-sip#20]
Hello,
is p2p-sip has a chance to be converted in python3?
I tried but stuck with bytes <-> string, impossible to make it p3 compatible
thanks

**Comment by theintencity** [comment]
Hi, there is a python3 contribution on the rtclite project, and the rtclite project is a superset of p2p-sip project. So I'll advise using that
https://github.com/theintencity/rtclite/tree/python3
